name: Build & Test Project

on:
  workflow_call:

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup Dotnet
        uses: ./.github/actions/setup-dotnet

      - name: Test Project
        shell: bash
        run: dotnet test --no-build --no-restore --verbosity minimal