name: Build & Test Project

on:
  workflow_call:

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup Dotnet
        uses: ./.github/actions/setup-dotnet
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION }}

      - name: Install Report Tool
        shell: bash
        run: dotnet tool install --global LiquidTestReports.Cli --version 2.0.0-beta.2

      - name: Test Project
        shell: bash
        run: dotnet test --configuration Release --no-build --no-restore --verbosity minimal

      - name: Generate Report
        if: always()
        shell: bash
        run: |
          liquid --inputs "File=**/*test-results.trx" --output-file results.md --title "${{ inputs.job_name }}"
          cat results.md >> $GITHUB_STEP_SUMMARY