name: Stryker Mutator

on:
  workflow_call:

jobs:
  dotnet-stryker:
    name: Stryker Mutator
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup Dotnet
        uses: ./.github/actions/setup-dotnet

      - name: Install Stryker Mutator
        shell: bash
        run: dotnet tool install dotnet-stryker --global

      - name: Run Stryker Mutator
        shell: bash
        run: dotnet stryker --reporter "cleartext" --reporter "html" --concurrency `nproc`

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: 'Stryker-Report'
          path: 'StrykerOutput/**/mutation-report.html'
          compression-level: '9'
          retention-days: 7